baseURL = "https://zqpei.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Ziqiang Pei"
theme = "hugo-theme-stack"
hasCJKLanguage = true

[pagination]
  pagerSize = 10

[permalinks]
  blog = "/blog/:slug/"
  page = "/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
